### ISSUE TITLE
array range check error

### ISSUE THREAD

**Issue by thorin72** [1ds/equiminer#3]
Only the lottery coin is available to mine.

**Comment by thorin72** [comment]
![array range check error](https://user-images.githubusercontent.com/38101550/38363655-11bdb712-3908-11e8-8cc7-ff195431b2ad.jpg)

**Comment by egyptianbman** [comment]
This is caused by EquiMiner not being able to pull information from the pool's api. I believe @NinjaPickle is working on a new version that loads a local copy of that data if the api connection fails. You might check to see if you have anti virus or firewall software or something blocking EquiMiner.

**Comment by thorin72** [comment]
Thank you egyptianbman.
